#!/usr/bin/env bash
# Pull Shopify env from Vercel (development target — production pull often returns empty locally).
set -euo pipefail

cd "$(dirname "$0")/.."
ENV_FILE=".env.local"
TMP=".env.vercel-pull.tmp"
BACKUP=".env.local.backup.$(date +%Y%m%d-%H%M%S)"
LOCAL_SITE_URL="${LOCAL_SITE_URL:-http://localhost:5555}"
VERCEL_SCOPE="${VERCEL_SCOPE:-h4ck3d}"
VERCEL_PROJECT="${VERCEL_PROJECT:-growmedicanextjs}"

if ! command -v vercel >/dev/null 2>&1; then
  echo "Chyba: nainstaluj Vercel CLI (npm i -g vercel) a spusti vercel login"
  exit 1
fi

if [[ ! -f .vercel/project.json ]]; then
  echo "Linkujem projekt ${VERCEL_PROJECT} (team ${VERCEL_SCOPE})..."
  vercel link --yes --project "$VERCEL_PROJECT" --scope "$VERCEL_SCOPE"
fi

if [[ -f "$ENV_FILE" ]]; then
  cp "$ENV_FILE" "$BACKUP"
  echo "Zaloha: $BACKUP"
fi

vercel env pull "$TMP" --environment=development --yes --scope "$VERCEL_SCOPE"

get_var() {
  local key="$1"
  local line val
  line=$(grep -E "^${key}=" "$TMP" | tail -1 || true)
  val="${line#*=}"
  val="${val#\"}"
  val="${val%\"}"
  printf '%s' "$val"
}

SHOPIFY_STORE_DOMAIN=$(get_var SHOPIFY_STORE_DOMAIN)
SHOPIFY_STOREFRONT_ACCESS_TOKEN=$(get_var SHOPIFY_STOREFRONT_ACCESS_TOKEN)
SHOPIFY_REVALIDATION_SECRET=$(get_var SHOPIFY_REVALIDATION_SECRET)
SHOPIFY_API_VERSION=$(get_var SHOPIFY_API_VERSION)

missing=()
[[ -z "$SHOPIFY_STORE_DOMAIN" ]] && missing+=("SHOPIFY_STORE_DOMAIN")
[[ -z "$SHOPIFY_STOREFRONT_ACCESS_TOKEN" ]] && missing+=("SHOPIFY_STOREFRONT_ACCESS_TOKEN")
[[ -z "$SHOPIFY_REVALIDATION_SECRET" ]] && missing+=("SHOPIFY_REVALIDATION_SECRET")
[[ -z "$SHOPIFY_API_VERSION" ]] && SHOPIFY_API_VERSION="2025-01"

if ((${#missing[@]})); then
  echo "Chyba: prazdne hodnoty z Vercel: ${missing[*]}"
  echo "Skus: vercel login && vercel teams switch h4ck3d && yarn pull:env"
  rm -f "$TMP"
  exit 1
fi

cat > "$ENV_FILE" <<EOF
# Shopify — server-side only (never commit)
# Generated by scripts/pull-env-from-vercel.sh ($(date -u +%Y-%m-%d))
SHOPIFY_STORE_DOMAIN=${SHOPIFY_STORE_DOMAIN}
SHOPIFY_STOREFRONT_ACCESS_TOKEN=${SHOPIFY_STOREFRONT_ACCESS_TOKEN}
SHOPIFY_REVALIDATION_SECRET=${SHOPIFY_REVALIDATION_SECRET}
SHOPIFY_API_VERSION=${SHOPIFY_API_VERSION}

# Local dev URL (Vercel production URL stays on Vercel only)
NEXT_PUBLIC_SITE_URL=${LOCAL_SITE_URL}
EOF

chmod 600 "$ENV_FILE"
rm -f "$TMP"

echo ""
echo "OK: $ENV_FILE z Vercel development env."
echo ""
echo "Kontrola (bez tokenov):"
grep -q '^SHOPIFY_STORE_DOMAIN=.' "$ENV_FILE" && echo "SHOPIFY_STORE_DOMAIN=PRESENT" || echo "SHOPIFY_STORE_DOMAIN=MISSING"
grep -E '^(SHOPIFY_API_VERSION|NEXT_PUBLIC_SITE_URL)=' "$ENV_FILE"
grep -q '^SHOPIFY_STOREFRONT_ACCESS_TOKEN=.' "$ENV_FILE" && echo "SHOPIFY_STOREFRONT_ACCESS_TOKEN=PRESENT" || echo "SHOPIFY_STOREFRONT_ACCESS_TOKEN=MISSING"
grep -q '^SHOPIFY_REVALIDATION_SECRET=.' "$ENV_FILE" && echo "SHOPIFY_REVALIDATION_SECRET=PRESENT" || echo "SHOPIFY_REVALIDATION_SECRET=MISSING"
