#!/usr/bin/env bash
# Create/update storefront .env.local for WordPress + WooCommerce (Shopify removed).
set -euo pipefail

cd "$(dirname "$0")/.."
ENV_FILE=".env.local"
BACKUP=".env.local.backup.$(date +%Y%m%d-%H%M%S)"

if [[ -f "$ENV_FILE" ]]; then
  cp "$ENV_FILE" "$BACKUP"
  echo "Backup: $BACKUP"
fi

read -r -p "WORDPRESS_BASE_URL [http://localhost:8080]: " wp_url
wp_url="${wp_url:-http://localhost:8080}"

read -r -p "WOO_CONSUMER_KEY: " woo_key
read -r -s -p "WOO_CONSUMER_SECRET: " woo_secret
echo
read -r -s -p "WORDPRESS_REVALIDATION_SECRET (min 16 chars): " reval
echo
read -r -p "NEXT_PUBLIC_SITE_URL [http://127.0.0.1:5555]: " site_url
site_url="${site_url:-http://127.0.0.1:5555}"

if [[ ${#reval} -lt 16 ]]; then
  echo "ERROR: WORDPRESS_REVALIDATION_SECRET must be at least 16 characters"
  exit 1
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-env.sh — WooCommerce only
WORDPRESS_BASE_URL=${wp_url}
WOO_CONSUMER_KEY=${woo_key}
WOO_CONSUMER_SECRET=${woo_secret}
WORDPRESS_REVALIDATION_SECRET=${reval}
NEXT_PUBLIC_SITE_URL=${site_url}
NEXT_PUBLIC_DEFAULT_LOCALE=sk
SITE_NOINDEX=1
NEXT_PUBLIC_DASHBOARD_MODE=agentic
DASHBOARD_AGENT_SECRET=$(openssl rand -hex 16)
# WOO_MOCK_MODE=1
# MISTRAL_API_KEY=
EOF

echo "Wrote $ENV_FILE (WooCommerce storefront)."
echo "Optional: set MISTRAL_API_KEY, CART_SIGNING_SECRET, SITE_NOINDEX=0 when indexing."
