#!/usr/bin/env bash
# Build gitignored env files from Cursor Cloud Agent Runtime Secrets (process.env).
# Never prints secret values.
#
# Required runtime vars:
#   DB_HOSTNAME, DB_USERNAME, DB_PASSWORD, DB_DATABASE
# Optional:
#   TABLE_PREFIX, ROOTDIR, WORDPRESS_BASE_URL, WOO_CONSUMER_KEY, WOO_CONSUMER_SECRET,
#   WORDPRESS_ADMIN_USER, WORDPRESS_APP_PASSWORD, WORDPRESS_REVALIDATION_SECRET
#
# Usage: ./scripts/bootstrap-runtime-secrets-env.sh

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

require_var() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    echo "ERROR: runtime secret $name is not set in process.env" >&2
    return 1
  fi
  echo "  OK: $name"
}

missing=0
echo "Checking runtime DB secrets..."
for v in DB_HOSTNAME DB_USERNAME DB_PASSWORD DB_DATABASE; do
  require_var "$v" || missing=$((missing + 1))
done
[[ "$missing" -eq 0 ]] || exit 1

DB_HOST="${DB_HOSTNAME}"
# WebSupport often uses host:port in wp-config
if [[ "$DB_HOST" != *:* ]] && [[ "${DB_PORT:-3306}" != "3306" ]]; then
  DB_HOST="${DB_HOST}:${DB_PORT}"
fi

WP_BASE="${WORDPRESS_BASE_URL:-${ROOTDIR:-https://cms.growmedica.cz}}"
WP_BASE="${WP_BASE%/}"

PROD_ENV="$ROOT/wordpress-production.local.env"
cat > "$PROD_ENV" <<EOF
# Generated by scripts/bootstrap-runtime-secrets-env.sh — DO NOT COMMIT
DB_NAME=${DB_DATABASE}
DB_USER=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}
DB_HOST=${DB_HOST}
TABLE_PREFIX=${TABLE_PREFIX:-wp_}
WORDPRESS_BASE_URL=${WP_BASE}
ROOTDIR=${ROOTDIR:-${WP_BASE}}
EOF

if [[ -n "${WOO_CONSUMER_KEY:-}" ]]; then
  echo "WOO_CONSUMER_KEY=${WOO_CONSUMER_KEY}" >> "$PROD_ENV"
fi
if [[ -n "${WOO_CONSUMER_SECRET:-}" ]]; then
  echo "WOO_CONSUMER_SECRET=${WOO_CONSUMER_SECRET}" >> "$PROD_ENV"
fi
if [[ -n "${WORDPRESS_ADMIN_USER:-}" ]]; then
  echo "WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}" >> "$PROD_ENV"
fi
if [[ -n "${WORDPRESS_APP_PASSWORD:-}" ]]; then
  echo "WORDPRESS_APP_PASSWORD=${WORDPRESS_APP_PASSWORD}" >> "$PROD_ENV"
fi
if [[ -n "${WORDPRESS_REVALIDATION_SECRET:-}" ]]; then
  echo "WORDPRESS_REVALIDATION_SECRET=${WORDPRESS_REVALIDATION_SECRET}" >> "$PROD_ENV"
fi

echo "Wrote $PROD_ENV (gitignored)"
echo "Bootstrap complete."
